// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.29.1
// source: linearize_models.proto

package linearize

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a field that can hold either a single integer or a nested array of integers
type UpdateMask struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Values        map[int32]*UpdateMaskValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMask) Reset() {
	*x = UpdateMask{}
	mi := &file_linearize_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMask) ProtoMessage() {}

func (x *UpdateMask) ProtoReflect() protoreflect.Message {
	mi := &file_linearize_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMask.ProtoReflect.Descriptor instead.
func (*UpdateMask) Descriptor() ([]byte, []int) {
	return file_linearize_models_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateMask) GetValues() map[int32]*UpdateMaskValue {
	if x != nil {
		return x.Values
	}
	return nil
}

// Holds a repeated list of UpdateMask, enabling deep nesting of arrays
type UpdateMaskValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A field that can be a single integer or a nested array of UpdateMask
	//
	// Types that are valid to be assigned to Value:
	//
	//	*UpdateMaskValue_Empty
	//	*UpdateMaskValue_Multiple
	Value         isUpdateMaskValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMaskValue) Reset() {
	*x = UpdateMaskValue{}
	mi := &file_linearize_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMaskValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMaskValue) ProtoMessage() {}

func (x *UpdateMaskValue) ProtoReflect() protoreflect.Message {
	mi := &file_linearize_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMaskValue.ProtoReflect.Descriptor instead.
func (*UpdateMaskValue) Descriptor() ([]byte, []int) {
	return file_linearize_models_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateMaskValue) GetValue() isUpdateMaskValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *UpdateMaskValue) GetEmpty() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Value.(*UpdateMaskValue_Empty); ok {
			return x.Empty
		}
	}
	return nil
}

func (x *UpdateMaskValue) GetMultiple() *UpdateMask {
	if x != nil {
		if x, ok := x.Value.(*UpdateMaskValue_Multiple); ok {
			return x.Multiple
		}
	}
	return nil
}

type isUpdateMaskValue_Value interface {
	isUpdateMaskValue_Value()
}

type UpdateMaskValue_Empty struct {
	// A empty struct
	Empty *emptypb.Empty `protobuf:"bytes,1,opt,name=empty,proto3,oneof"`
}

type UpdateMaskValue_Multiple struct {
	// A nested array of UpdateMask, allowing deep nesting
	Multiple *UpdateMask `protobuf:"bytes,2,opt,name=multiple,proto3,oneof"`
}

func (*UpdateMaskValue_Empty) isUpdateMaskValue_Value() {}

func (*UpdateMaskValue_Multiple) isUpdateMaskValue_Value() {}

var File_linearize_models_proto protoreflect.FileDescriptor

var file_linearize_models_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x69, 0x7a, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x72,
	0x69, 0x7a, 0x65, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x9e, 0x01, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x73, 0x6b, 0x12,
	0x39, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x69, 0x7a, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4d, 0x61, 0x73, 0x6b, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0x55, 0x0a, 0x0b, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x30, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6c, 0x69, 0x6e,
	0x65, 0x61, 0x72, 0x69, 0x7a, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x73,
	0x6b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x7f, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x73, 0x6b, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x48, 0x00, 0x52, 0x05, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x33, 0x0a, 0x08, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x69,
	0x7a, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x73, 0x6b, 0x48, 0x00, 0x52,
	0x08, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x42, 0x1c, 0x5a, 0x1a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x66, 0x67, 0x72, 0x7a, 0x6c, 0x2f, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x69, 0x7a, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_linearize_models_proto_rawDescOnce sync.Once
	file_linearize_models_proto_rawDescData = file_linearize_models_proto_rawDesc
)

func file_linearize_models_proto_rawDescGZIP() []byte {
	file_linearize_models_proto_rawDescOnce.Do(func() {
		file_linearize_models_proto_rawDescData = protoimpl.X.CompressGZIP(file_linearize_models_proto_rawDescData)
	})
	return file_linearize_models_proto_rawDescData
}

var file_linearize_models_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_linearize_models_proto_goTypes = []any{
	(*UpdateMask)(nil),      // 0: linearize.UpdateMask
	(*UpdateMaskValue)(nil), // 1: linearize.UpdateMaskValue
	nil,                     // 2: linearize.UpdateMask.ValuesEntry
	(*emptypb.Empty)(nil),   // 3: google.protobuf.Empty
}
var file_linearize_models_proto_depIdxs = []int32{
	2, // 0: linearize.UpdateMask.values:type_name -> linearize.UpdateMask.ValuesEntry
	3, // 1: linearize.UpdateMaskValue.empty:type_name -> google.protobuf.Empty
	0, // 2: linearize.UpdateMaskValue.multiple:type_name -> linearize.UpdateMask
	1, // 3: linearize.UpdateMask.ValuesEntry.value:type_name -> linearize.UpdateMaskValue
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_linearize_models_proto_init() }
func file_linearize_models_proto_init() {
	if File_linearize_models_proto != nil {
		return
	}
	file_linearize_models_proto_msgTypes[1].OneofWrappers = []any{
		(*UpdateMaskValue_Empty)(nil),
		(*UpdateMaskValue_Multiple)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_linearize_models_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_linearize_models_proto_goTypes,
		DependencyIndexes: file_linearize_models_proto_depIdxs,
		MessageInfos:      file_linearize_models_proto_msgTypes,
	}.Build()
	File_linearize_models_proto = out.File
	file_linearize_models_proto_rawDesc = nil
	file_linearize_models_proto_goTypes = nil
	file_linearize_models_proto_depIdxs = nil
}
