// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.29.2
// source: linearize_models.proto

package linearize

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateMaskOperation int32

const (
	UpdateMaskOperation_ADD    UpdateMaskOperation = 0
	UpdateMaskOperation_UPDATE UpdateMaskOperation = 1
	UpdateMaskOperation_REMOVE UpdateMaskOperation = 2
)

// Enum value maps for UpdateMaskOperation.
var (
	UpdateMaskOperation_name = map[int32]string{
		0: "ADD",
		1: "UPDATE",
		2: "REMOVE",
	}
	UpdateMaskOperation_value = map[string]int32{
		"ADD":    0,
		"UPDATE": 1,
		"REMOVE": 2,
	}
)

func (x UpdateMaskOperation) Enum() *UpdateMaskOperation {
	p := new(UpdateMaskOperation)
	*p = x
	return p
}

func (x UpdateMaskOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateMaskOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_linearize_models_proto_enumTypes[0].Descriptor()
}

func (UpdateMaskOperation) Type() protoreflect.EnumType {
	return &file_linearize_models_proto_enumTypes[0]
}

func (x UpdateMaskOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateMaskOperation.Descriptor instead.
func (UpdateMaskOperation) EnumDescriptor() ([]byte, []int) {
	return file_linearize_models_proto_rawDescGZIP(), []int{0}
}

type UpdateMask struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Values        map[int32]*UpdateMaskValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMask) Reset() {
	*x = UpdateMask{}
	mi := &file_linearize_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMask) ProtoMessage() {}

func (x *UpdateMask) ProtoReflect() protoreflect.Message {
	mi := &file_linearize_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMask.ProtoReflect.Descriptor instead.
func (*UpdateMask) Descriptor() ([]byte, []int) {
	return file_linearize_models_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateMask) GetValues() map[int32]*UpdateMaskValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type UpdateMaskValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Masks         *UpdateMask            `protobuf:"bytes,1,opt,name=masks,proto3" json:"masks,omitempty"`
	Op            UpdateMaskOperation    `protobuf:"varint,2,opt,name=op,proto3,enum=linearize.UpdateMaskOperation" json:"op,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMaskValue) Reset() {
	*x = UpdateMaskValue{}
	mi := &file_linearize_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMaskValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMaskValue) ProtoMessage() {}

func (x *UpdateMaskValue) ProtoReflect() protoreflect.Message {
	mi := &file_linearize_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMaskValue.ProtoReflect.Descriptor instead.
func (*UpdateMaskValue) Descriptor() ([]byte, []int) {
	return file_linearize_models_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateMaskValue) GetMasks() *UpdateMask {
	if x != nil {
		return x.Masks
	}
	return nil
}

func (x *UpdateMaskValue) GetOp() UpdateMaskOperation {
	if x != nil {
		return x.Op
	}
	return UpdateMaskOperation_ADD
}

var File_linearize_models_proto protoreflect.FileDescriptor

var file_linearize_models_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x69, 0x7a, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x72,
	0x69, 0x7a, 0x65, 0x22, 0x9e, 0x01, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61,
	0x73, 0x6b, 0x12, 0x39, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x69, 0x7a, 0x65, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x73, 0x6b, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0x55, 0x0a,
	0x0b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x30,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x6c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x69, 0x7a, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4d, 0x61, 0x73, 0x6b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x6e, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61,
	0x73, 0x6b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x6d, 0x61, 0x73, 0x6b, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x69,
	0x7a, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x73, 0x6b, 0x52, 0x05, 0x6d,
	0x61, 0x73, 0x6b, 0x73, 0x12, 0x2e, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1e, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x69, 0x7a, 0x65, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4d, 0x61, 0x73, 0x6b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x02, 0x6f, 0x70, 0x2a, 0x36, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61,
	0x73, 0x6b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x07, 0x0a, 0x03, 0x41,
	0x44, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x01,
	0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x10, 0x02, 0x42, 0x1c, 0x5a, 0x1a,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x67, 0x72, 0x7a, 0x6c,
	0x2f, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x69, 0x7a, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_linearize_models_proto_rawDescOnce sync.Once
	file_linearize_models_proto_rawDescData = file_linearize_models_proto_rawDesc
)

func file_linearize_models_proto_rawDescGZIP() []byte {
	file_linearize_models_proto_rawDescOnce.Do(func() {
		file_linearize_models_proto_rawDescData = protoimpl.X.CompressGZIP(file_linearize_models_proto_rawDescData)
	})
	return file_linearize_models_proto_rawDescData
}

var file_linearize_models_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_linearize_models_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_linearize_models_proto_goTypes = []any{
	(UpdateMaskOperation)(0), // 0: linearize.UpdateMaskOperation
	(*UpdateMask)(nil),       // 1: linearize.UpdateMask
	(*UpdateMaskValue)(nil),  // 2: linearize.UpdateMaskValue
	nil,                      // 3: linearize.UpdateMask.ValuesEntry
}
var file_linearize_models_proto_depIdxs = []int32{
	3, // 0: linearize.UpdateMask.values:type_name -> linearize.UpdateMask.ValuesEntry
	1, // 1: linearize.UpdateMaskValue.masks:type_name -> linearize.UpdateMask
	0, // 2: linearize.UpdateMaskValue.op:type_name -> linearize.UpdateMaskOperation
	2, // 3: linearize.UpdateMask.ValuesEntry.value:type_name -> linearize.UpdateMaskValue
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_linearize_models_proto_init() }
func file_linearize_models_proto_init() {
	if File_linearize_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_linearize_models_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_linearize_models_proto_goTypes,
		DependencyIndexes: file_linearize_models_proto_depIdxs,
		EnumInfos:         file_linearize_models_proto_enumTypes,
		MessageInfos:      file_linearize_models_proto_msgTypes,
	}.Build()
	File_linearize_models_proto = out.File
	file_linearize_models_proto_rawDesc = nil
	file_linearize_models_proto_goTypes = nil
	file_linearize_models_proto_depIdxs = nil
}
